stages:
  - build
  - deploy

Build Site:
  image: node:latest
  stage: build
  tags: ["docker"]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
  before_script:
    - npm install
  script:
    - npm run build

Webhoster:
  stage: deploy
  tags: ["docker"]
  image:
    name: alpacadb/docker-lftp
    entrypoint: [""]
  script:
    - lftp -d -e "set ftp:ssl-allow false; mirror -eRnv dist /; exit;" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  only:
    - refactoring
    - refactoring-ci-cd
  when: manual
